<?php

$titles = array(
1 => "If someone Car DM'ed you, what the right thing you should do ?",
"You just landed in Los Santos, and a few seconds later you are being knucked out by some gangsters.",
"What's the right combination to use /me command ?",
"What is the result for using third-party programs \ hacks ?",
"What is the right level to use metagame ?",
"Is powergaming basically calling players they first names ?",
"What's the right price which you can rob at ?",
"What does 'RP' stand for ?",
"Someone is insulting you in our Ventrilo, what will you do ?",
"What is our statute about roleplay names ?"
);

$ans1 = array(
1 => "I'll pull him outside of his car ninja jacking, punching and kicking till death.",
"It's Deathmatch ! It's against the rule ! I'll absolutely report them without even thinking.",
"/me appears to be sixteen.",
"We don't have anything against hacks. It's allowed, and it's better then fun.",
"You can't metagame. It is not allowed, it's bad example of roleplaying.",
"Yes, that's what powergaming stands for.",
"I can rob until 15,000 dollars.",
"Revenge of Pokemon.",
"Does it a question ? I'll insult him as hard as I can, who is he ?!",
"No law, who cares. I can even log in as ronald_brown."
);

$ans2 = array(
1 => "I'll take a photo of the incident using F8, patientlly reporting by using /re.",
"I'll take out a gun without any roleplay manner, and I'll shoot everyone of those gangsters. They doesn't have right to touch me.",
"/me roleplaying at Infinity Roleplay Community.",
"My account and my IP address will be blocked, I'll be banned. For ever, and I won't have a chance to come back.",
"If you reached level 3, you are free to metagame, it's just a game. You can meta whenever you want.",
"No, powergaming is using OOC knowledge IC.",
"I can rob until 50,000.",
"Role play.",
"I'll use Record Program to record what he says, and he will be punished for insulting.",
"I have to log in using a celebrities's name, as Tal_Musseri or Oded_Menashe."
);

$ans3 = array(
1 => "I'll shout at admins using /report, flooding admins private messages waiting to a respond.",
"I'll ask them calmly, why are they attacking me, if I didn't done nothing, it might be IC'ly, I'll keep roleplay as necessary.",
"/me raises his left hand, looking towards his clock.",
"I'll be kicked for that. It is not allowed.",
"You can metagame from level 1, using commands as : /me reaches his metagaming device which located in his pocket.",
"No, that's not powergaming. Powergaming is use of unrealistic commands and actions, that's Metagaming.",
"This is not a question at all, I can rob whenever and whoever I want as any price as I want to rob.",
"Rain of Peace.",
"I'll page flood all the approaches owners in our ventrilo until someone will come to my room.",
"I MUST log in to our server using a big letter at the start of any name, surname or forename, as Haim_Elbaz."
);

$right_answer = array(
1 => "b",
"c",
"c",
"b",
"a",
"c",
"b",
"b",
"b",
"c"
);

?>