<?php

$job_title = array(
0=>"None",
1=>"Los Santos Police Department",
2=>"Los Santos Emergency Service",
3=>"Los Santos Transportation",
4=>"Los Santos News",
5=>"Fisherman",
6=>"Pizza Boy",
7=>"Los Santos Mechanic",
8=>"Arms Dealer",
15=>"Federal Bureau of Investigation",
17=>"Los Santos Fire Department",
18=>"Newspaper Deliver",
19=>"Garbage Man
");

$job_name = array(
0=>"None",
1=>"LSPD",
2=>"LSES",
3=>"Transportation",
4=>"News",
5=>"Fisherman",
6=>"Pizzaboy",
7=>"Mechanic",
8=>"Arms Dealer",
15=>"FBI",
17=>"LSFD",
18=>"Newspaper Deliver",
19=>"Garbage Man"
);

$factions = array(1=>"LSPD",17=>"LSFD",2=>"LSES",15=>"FBI",7=>"Mechanic",4=>"News",3=>"Transportation");

$factions['LSPD'] = array(1 => "Chief",
2 => "Deputy Of Chief",
3=> "Captain",
4=> "Lieutenant",
5=> "Sergeant",
6=> "Commander",
7=> "Inspector",
8=> "Corporal",
9=> "Advanced Officer",
10=> "Trainee",
11=> "Cadet",
12=>"Trainee"
);

$factions['LSFD'] = array(1 => "Captain",
8 => "FireFighter"
);

$factions['LSES'] = array(1 => "Manager",
3 => "Doctor",
4 => "Paramedic",
5 => "Medic",
8 => "Trainee"
);

$factions['FBI'] = array(1 => "Director",	
2 => "Deputy Of Director",
3 => "Senior Agent",
4 => "Special Agent",
5 => "Agent",
6 => "Trainee"
);

$factions['Mechanic'] = array(6 => "Manager",
7 =>"Merchant",
12 => "Mechanic");

$factions['News'] = array(6 => "Manager",
7 => "Field Reporter",
8 => "Editor",
9 => "Reporter"
);

$factions['Transportation'] = array(6 => "Manager",
3 => "Usher",
7 => "BusD",
8 => "TaxiD"
);

?>